const zh = {
  lang: 'zh',
  htmlLang: 'zh-Hans',
  locale: 'zh_CN',
  path: 'zh',
  altLangLabel: 'EN',
  altLangName: 'English version',
  meta: {
    title: 'Mara Ellison — 里斯本创意前端开发者 & WebGL 工程师',
    description:
      'Mara Ellison 的作品集：常驻里斯本的创意前端开发者，为全球产品团队与设计工作室打造快速、无障碍的 React、Next.js 与 WebGL 交互体验。',
    keywords: '创意前端开发, WebGL 开发, React 开发者, Next.js, Three.js, 交互设计, 里斯本, 作品集',
    ogAlt: 'Mara Ellison — 创意前端开发者作品集',
  },
  a11y: {
    skip: '跳到主要内容',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    themeToLight: '切换到浅色模式',
    themeToDark: '切换到深色模式',
    home: 'Mara Ellison，回到顶部',
    primaryNav: '主导航',
  },
  nav: [
    { id: 'about', label: '关于' },
    { id: 'skills', label: '技能' },
    { id: 'work', label: '作品' },
    { id: 'experience', label: '经历' },
    { id: 'blog', label: '博客' },
    { id: 'contact', label: '联系' },
  ],
  headerCta: '聊聊项目',
  loader: '作品集加载中',
  hero: {
    status: '2026 年 11 月起可接新项目',
    eyebrow: 'Mara Ellison，创意前端开发者',
    lines: [
      [{ t: '打造' }, { t: '有趣、', em: true }],
      [{ t: '高性能的' }],
      [{ t: '网页' }, { t: '体验。' }],
    ],
    intro: '我是常驻里斯本的 React 与 WebGL 工程师，帮助产品团队和设计工作室交付“有生命感”的界面——同时不牺牲 Core Web Vitals 与无障碍体验。',
    primary: '浏览作品',
    secondary: '开始合作',
    now: '最近',
    nowText: '正在为 Nordlys Outdoor 开发 WebGL 产品配置器',
    scroll: '向下滚动探索 • 向下滚动探索 • ',
    stats: [
      { value: 11, suffix: '+', label: '年网页创作经验' },
      { value: 60, suffix: '+', label: '个上线产品' },
      { value: 9, suffix: '', label: '项行业奖项' },
      { value: 98, suffix: '', label: 'Lighthouse 平均分' },
    ],
  },
  about: {
    kicker: '01 — 关于',
    title: '设计师的眼光，工程师的严谨。',
    portraitAlt: 'Mara Ellison 的插画肖像：创意前端开发者，戴圆框眼镜、穿铁锈色高领毛衣',
    badge: '你好，我是 Mara',
    bio: [
      '我在波尔图从平面设计起步，为了让版式动起来而学会了写代码。十一年后，我负责的是产品里最让人记住的部分：顺滑的新手引导、一目了然的数据面板，以及让品牌“活起来”的 WebGL 瞬间。',
      '如今我以独立开发者身份，与四大洲的产品团队和工作室合作。我在意那些看不见的细节——焦点状态、减少动态效果的降级方案、中端手机上的 60 fps——因为手艺正是在这些地方变成信任。',
    ],
    facts: [
      ['常驻', '葡萄牙里斯本（UTC+0）'],
      ['语言', '英语、葡萄牙语、德语'],
      ['屏幕之外', '模块合成器与抱石攀岩'],
    ],
    storyTitle: '一路走来',
    story: [
      { year: '2013', title: '像素与印刷', text: '传达设计学位、一篇关于生成式字体的毕业论文，以及第一段手写的 JavaScript 动画。' },
      { year: '2016', title: '柏林与 WebGL', text: '加入 Kraft & Pixel，为汽车和时尚品牌打造屡获殊荣的 WebGL 营销项目。' },
      { year: '2019', title: '规模化产品', text: '在伦敦 Northwind Finance 带领前端：设计系统、性能预算和一支八人团队。' },
      { year: '2022', title: '独立执业', text: '在里斯本开设一人工作室，与九个国家的团队合作。' },
      { year: '现在', title: '分享与开源', text: '在大会演讲、写博客，并维护开源动效工具 Kinetic Type。' },
    ],
  },
  skills: {
    kicker: '02 — 技能',
    title: '为手艺与速度调校的工具箱。',
    intro: '将鼠标悬停或聚焦在任一技能上查看说明；点击词云中的词语，看看我在哪里用到它。',
    radarTitle: '能力图谱',
    radarLabels: ['前端工程', '创意编程', '用户体验与交互', '性能优化', '无障碍', '设计系统'],
    barsTitle: '核心技术熟练度',
    cloudTitle: '常用工具',
    cloudHint: '点击词语',
    cloudEmpty: '从词云中选一个词，看看它在我的工作中扮演什么角色。',
    cloudNotes: {
      React: '2015 年起的主力框架——从类组件一路用到并发渲染。',
      'Next.js': '产品官网与数据面板的混合渲染方案；这个作品集就运行在它上面。',
      TypeScript: '处处开启 strict 模式；类型是永不过期的文档。',
      'Three.js': '为营销项目和数据地球仪打造场景、着色器与后期处理。',
      CSS: '容器查询、层叠层，以及对“层叠”本身的敬畏。',
      WebGL: '当 Three.js 太重或不够用时，直接写底层渲染。',
      GLSL: '为转场、噪声场和粒子系统手写着色器。',
      Astro: '内容型网站和本博客：岛屿架构、内容集合、零 JS 页面。',
      'Framer Motion': 'React 界面的布局动画与手势。',
      GSAP: '复杂滚动联动序列的时间线编排。',
      Accessibility: '以 WCAG 2.2 AA 为底线，读屏实测，键盘优先。',
      Performance: '性能预算、Core Web Vitals，以及真机性能分析。',
      'Design Systems': '可跨团队扩展的设计令牌、基础组件与文档。',
      Figma: '与设计师一起制作动效原型、交接设计令牌。',
      'Node.js': '构建工具、API 与图片处理流水线。',
      'Web Audio': '生成式声景——包括本页的背景音乐播放器。',
      'D3.js': '自定义比例尺与过渡的数据可视化。',
      SVG: '图标、插画与路径变形。',
      'Canvas API': '2D 生成艺术与高速像素处理。',
      Storybook: '组件工作台与视觉回归测试。',
      Vite: '极速开发服务器与组件库构建。',
      Playwright: 'CI 中的端到端与跨浏览器测试。',
      WebXR: 'AR 商品预览原型。',
      Svelte: '用于嵌入场景的小而快的组件。',
      Blender: '为实时场景建模与烘焙资源。',
      i18n: '支持 hreflang、ICU 消息与 RTL 的多语言网站。',
      SEO: '结构化数据、可抓取渲染与站点地图。',
      'Motion Design': '缓动、编排——意义大于装饰。',
      Tailwind: '在客户设计系统上快速搭原型。',
      Shopify: '基于 Storefront API 的无头电商。',
    },
    chipsTitle: '招牌技能',
    chips: [
      { name: 'React', years: '11 年', note: '组件架构、并发特性、自定义 Hook 与性能分析。' },
      { name: 'TypeScript', years: '8 年', note: '为设计系统与数据密集型面板提供严格类型。' },
      { name: 'Three.js', years: '8 年', note: '实时 3D、自定义材质、实例化渲染与后期处理。' },
      { name: 'GLSL', years: '7 年', note: '手写转场、噪声与粒子着色器。' },
      { name: '动效', years: '10 年', note: 'Framer Motion、GSAP 与 CSS——始终提供减少动态效果的降级。' },
      { name: '无障碍', years: '9 年', note: 'WCAG 2.2 AA 审计、焦点管理与读屏测试。' },
      { name: '性能', years: '9 年', note: '性能预算、懒加载、图片流水线与 Core Web Vitals。' },
      { name: '设计系统', years: '6 年', note: '设计令牌、主题、文档与跨团队推广。' },
      { name: 'Astro', years: '3 年', note: '岛屿架构、内容集合与静态生成。' },
      { name: 'Node.js', years: '7 年', note: '工具链、API 与构建流水线。' },
    ],
  },
  work: {
    kicker: '03 — 精选作品',
    title: '打动人心，也打动指标。',
    intro: '客户项目、自有产品与开源工具精选。点开任一项目查看完整故事。',
    all: '全部',
    categories: {
      'web-app': 'Web 应用',
      webgl: 'WebGL 与 3D',
      ecommerce: '电商',
      'design-system': '设计系统',
      'open-source': '开源',
    },
    view: '查看项目',
    role: '角色',
    client: '客户',
    year: '年份',
    stack: '技术栈',
    results: '成果',
    caseStudy: '阅读相关文章',
    similar: '开始一个类似项目',
    prev: '上一个项目',
    next: '下一个项目',
    close: '关闭项目详情',
    webglHint: 'WebGL 转场 — 可用 ← → 键切换',
    items: {
      aurora: {
        title: 'Aurora — 实时银行数据面板',
        summary: '为 200 万+ 企业银行客户打造的平静、一眼可读的面板。',
        client: 'Northwind Finance',
        role: '前端负责人',
        description: 'Aurora 用基于 Next.js 与 D3 的流式面板取代了一个用了十年的旧门户。我们设计了一套一眼可读的图表语法，并用性能预算把每个路由的 JavaScript 控制在 170 kB 以内。',
        results: ['LCP 从 4.1 秒降到 1.6 秒', '可用性测试中获取洞察的速度提升 38%', '两个季度内 NPS 提升 22 分'],
      },
      lumen: {
        title: 'Lumen UI — 设计系统入门套件',
        summary: '设计令牌、60+ 无障碍组件与文档，开箱即用。',
        client: '自有产品',
        role: '作者与维护者',
        description: 'Lumen UI 是一套商业入门套件，面向需要快速建立正式设计系统的团队：与 Figma 同步的设计令牌、基于 Radix 的基础组件、主题能力，以及为每个组件附上无障碍说明的 Storybook 文档。',
        results: ['1,800+ 个团队在用', '320 条评价，平均 4.9 ★', '开箱即符合 WCAG 2.2 AA'],
      },
      tidal: {
        title: 'Tidal — 海洋温度地球仪',
        summary: '在交互式 WebGL 地球上呈现四十年的海表温度数据。',
        client: 'Blue Current Foundation',
        role: '创意开发',
        description: 'Tidal 把 NOAA 四十年的海表温度数据流式载入自定义 GLSL 地球。数据解码在 Web Worker 中进行，渲染器会自适应分辨率，在五年前的手机上也能保持 60 fps。',
        results: ['上线首月 120 万访问', '被两家全国性报纸报道', '中端安卓机 60 fps'],
      },
      nordlys: {
        title: 'Nordlys — 3D 户外装备配置器',
        summary: '实时定制夹克和背包，一键完成下单。',
        client: 'Nordlys Outdoor',
        role: '前端与 WebGL 负责人',
        description: '基于无头 Shopify 的店铺，搭配 Three.js 配置器：面料、颜色和五金件的变化借助烘焙光照与压缩纹理即时渲染，每一种配置都有可分享的链接。',
        results: ['首季度转化率 +31%', '定制商品退货率 −22%', 'CSS Design Awards 2024 最佳 UI'],
      },
      sonic: {
        title: 'Sonic Garden — 生成式声光装置',
        summary: '一间让观众“种出”声音与光之花园的展厅。',
        client: 'Museu de Luz',
        role: '创意技术',
        description: 'Sonic Garden 将观众的动作转化为生成式音乐，以及投影在三面墙上的 WebGL 花园。它在单个浏览器标签页里无人值守地运行了六个月——没有崩溃，没有重启。',
        results: ['平均停留时长提升 3 倍', '连续运行 180 天', '4.8 万名观众'],
      },
      kinetic: {
        title: 'Kinetic Type — 动态字体工具',
        summary: '开源的动态字体试验场，可导出为视频或代码。',
        client: '开源',
        role: '作者与维护者',
        description: 'Kinetic Type 让设计师用弹簧和缓动曲线编排文字动画，并导出 MP4、Lottie 或 React 代码。它基于 Framer Motion 与 Canvas 渲染器，预览流畅。',
        results: ['GitHub 4.2k 星', '120+ 位贡献者', '被 3 门大学课程采用'],
      },
      atlas: {
        title: 'Atlas — 离线优先的旅行手账',
        summary: '即使没有信号，地图、笔记和照片也随时可用的 PWA。',
        client: 'Atlas Labs',
        role: '前端工程师',
        description: 'Atlas 通过 IndexedDB 与后台同步保存手账，并沿计划路线缓存矢量地图瓦片，让旅行者在火车上、山里甚至飞机上都能继续记录。',
        results: ['应用商店评分 4.8 ★', '周留存 65%', '全部功能支持离线'],
      },
      pulse: {
        title: 'Pulse — 无障碍健康引导流程',
        summary: '无论能力如何，每个人都能顺利完成的注册引导。',
        client: 'Pulse Health',
        role: '无障碍与体验工程师',
        description: '我们把 Pulse 的注册引导重写为状态机：显式的焦点管理、平实的文案，以及 CI 中自动运行的 axe-core 检查。如今读屏用户完成注册的速度与其他人一样快。',
        results: ['完成率从 54% 提升到 86%', 'Lighthouse 无障碍分 61 → 100', '零严重 WCAG 问题'],
      },
      orbit: {
        title: 'Orbit 26 — 大会官网与票务',
        summary: '宇宙主题 WebGL 首屏、讲者 CMS 与两步购票流程。',
        client: 'Orbit Conf',
        role: '创意开发',
        description: 'Orbit 的网站把 Astro 内容后台与一个随日程变化的 Three.js 太阳系结合在一起。门票通过两步 Stripe 结账售出，即使没有 JavaScript 也能完成购买。',
        results: ['提前 3 周售罄', '所有页面 CLS 0.02', 'Awwwards 每日最佳网站'],
      },
    },
  },
  testimonials: {
    kicker: '04 — 客户评价',
    title: '深受交付型团队信赖。',
    ratingLabel: '5 星（满分 5 星）',
    prev: '上一条评价',
    next: '下一条评价',
    pauseHint: '鼠标悬停时自动播放会暂停',
    items: {
      priya: { role: '产品副总裁', quote: 'Mara 把一个信息密集的金融面板变成了客户真心喜欢用的产品。页面加载时间减半，NPS 提升了 22 分。' },
      tomas: { role: '创意总监', quote: '工程师与艺术家的罕见结合。她做的 WebGL 地球仪成了我们整场活动的核心——在五年前的手机上依然流畅。' },
      hannah: { role: '设计系统负责人', quote: 'Lumen UI 为我们团队省下了好几个月。它的设计令牌、文档和无障碍默认值是我见过最好的入门套件。' },
      daniel: { role: '首席技术官', quote: '她在意那些别人看不到的细节——焦点状态、减少动态效果、加载骨架屏。我们的 Lighthouse 分数从 61 提升到了 99。' },
      sofie: { role: '电商负责人', quote: '3D 配置器上线第一个季度就让转化率提升了 31%。跨三个时区和 Mara 合作非常愉快。' },
      ines: { role: '策展人', quote: '观众停留的时间是以往任何展览的三倍。Sonic Garden 仿佛是活的，而且六个月里一次都没有崩溃。' },
    },
  },
  experience: {
    kicker: '05 — 经历',
    title: '一份可交互的简历。',
    intro: '筛选时间线，展开任一条目查看详情。',
    filters: { all: '全部', work: '工作', education: '教育', award: '奖项', talk: '演讲' },
    more: '展开详情',
    less: '收起详情',
    present: '至今',
    items: [
      {
        id: 'independent', type: 'work', start: '2022', end: null,
        title: '独立创意开发者 & 工作室合伙人', org: 'Mara Ellison Studio', place: '里斯本 · 远程',
        summary: '与产品团队和工作室合作，打造交互产品、WebGL 体验与设计系统。',
        details: ['为九个国家的客户交付 25+ 个项目', '创建设计系统入门套件 Lumen UI，1,800+ 个团队在用', '担任两家前端训练营导师'],
        tags: ['Next.js', 'Astro', 'Three.js', 'TypeScript'],
      },
      {
        id: 'northwind', type: 'work', start: '2019', end: '2022',
        title: '高级前端负责人', org: 'Northwind Finance', place: '英国伦敦',
        summary: '主导重建服务 200 万客户的企业银行面板。',
        details: ['组建并带领八人工程团队', '引入性能预算：LCP 从 4.1 秒降到 1.6 秒', '搭建公司第一套设计系统（60+ 组件）'],
        tags: ['React', 'D3.js', 'GraphQL', 'Storybook'],
      },
      {
        id: 'kraft', type: 'work', start: '2016', end: '2019',
        title: '交互开发工程师', org: 'Kraft & Pixel Studio', place: '德国柏林',
        summary: '为汽车与时尚品牌打造 WebGL 营销活动与新品发布页。',
        details: ['四次获得 Awwwards 每日最佳网站', '用 WebXR 制作 AR 商品预览原型', '主持工作室内部的着色器俱乐部'],
        tags: ['Three.js', 'GLSL', 'GSAP', 'WebXR'],
      },
      {
        id: 'mosaic', type: 'work', start: '2014', end: '2016',
        title: '前端开发工程师', org: 'Mosaic Labs', place: '葡萄牙波尔图',
        summary: '为三十多家客户交付响应式网站与 Web 应用。',
        details: ['2015 年率先采用 React 并担任内部讲师', '推行组件驱动开发与视觉测试'],
        tags: ['React', 'Sass', 'Node.js'],
      },
      {
        id: 'porto', type: 'education', start: '2009', end: '2013',
        title: '传达设计学士', org: '波尔图大学美术学院', place: '葡萄牙波尔图',
        summary: '字体排印、交互与生成式设计。',
        details: ['毕业论文：《面向屏幕的生成式字体》', '优秀毕业生'],
        tags: ['字体排印', 'Processing'],
      },
      {
        id: 'cssda', type: 'award', start: '2024', end: null,
        title: 'CSS Design Awards — 最佳 UI', org: 'Nordlys 3D 配置器', place: '线上',
        summary: '因界面设计、易用性与创新获得认可。',
        details: ['同时入围最佳创新奖', '案例登上 CSSDA 通讯'],
        tags: ['电商', 'WebGL'],
      },
      {
        id: 'awwwards', type: 'award', start: '2017', end: '2025',
        title: 'Awwwards 每日最佳 ×5 · FWA 每日最佳 ×3', org: '多个客户项目', place: '线上',
        summary: '在营销活动与产品网站上的创意开发获得认可。',
        details: ['Orbit 26 — 2025 每日最佳网站', 'Tidal — 2023 开发者奖'],
        tags: ['创意开发'],
      },
      {
        id: 'motion-talk', type: 'talk', start: '2026', end: null,
        title: '《有意义的动效》— Web Motion Summit', org: '即将举行 · 2026 年 11 月 12 日', place: '里斯本 LX Factory',
        summary: '如何设计“解释而非装饰”的动效系统。',
        details: ['45 分钟演讲，含现场演示', '演讲后在博客公开幻灯片与代码'],
        tags: ['动效', '设计系统'],
      },
      {
        id: 'shader-talk', type: 'talk', start: '2023', end: null,
        title: '《写给前端开发者的着色器》', org: 'Frontend Porto', place: '葡萄牙波尔图',
        summary: '面向已经会 CSS 的人的 GLSL 入门。',
        details: ['2023 季观看次数最多的演讲', '工作坊版本已培训 300+ 名开发者'],
        tags: ['GLSL', 'WebGL'],
      },
    ],
    eventsTitle: '即将举行的演讲与工作坊',
    addToCalendar: '添加到日历',
    online: '线上',
    events: {
      'motion-summit': { name: '有意义的动效 — Web Motion Summit 2026', description: '关于设计“解释而非装饰”的动效系统的演讲，含 React 与 GSAP 现场演示。', place: '里斯本 LX Factory' },
      'webgl-workshop': { name: '前端开发者的 WebGL 实战工作坊', description: '三小时线上工作坊：从第一个着色器到可上线的 Three.js 转场。', place: '线上（Zoom）' },
    },
  },
  globe: {
    kicker: '06 — 足迹',
    title: '我工作过的地方。',
    intro: '横跨四大洲的客户与合作。拖动地球，或点选一座城市。',
    stats: [['11', '座城市'], ['4', '个大洲'], ['60+', '位合作者']],
    home: '大本营',
    loading: '交互地球加载中…',
    places: {
      lisbon: ['里斯本', '大本营与工作室 · 2022 年至今'],
      porto: ['波尔图', 'Mosaic Labs · 2014–2016'],
      london: ['伦敦', 'Northwind Finance · 2019–2022'],
      berlin: ['柏林', 'Kraft & Pixel Studio · 2016–2019'],
      stockholm: ['斯德哥尔摩', 'Nordlys Outdoor · 2024'],
      newyork: ['纽约', 'Pulse Health · 2025'],
      sanfrancisco: ['旧金山', 'Fieldnote 与 Lumen UI · 2025'],
      saopaulo: ['圣保罗', 'Orbit Conf · 2025'],
      tokyo: ['东京', 'Kinetic Type 贡献者峰会 · 2023'],
      singapore: ['新加坡', 'Aurora 亚太发布 · 2024'],
      sydney: ['悉尼', 'Blue Current Foundation · 2023'],
    },
  },
  blog: {
    kicker: '07 — 写作',
    title: '关于手艺、代码与动效的笔记。',
    intro: '关于 WebGL、性能、动效设计与 Web 平台的长文（英文）。',
    featured: '精选',
    readArticle: '阅读文章',
    minRead: '分钟阅读',
    latest: '最新文章',
    all: '浏览全部文章',
    rss: '通过 RSS 订阅',
    prev: '上一篇精选文章',
    next: '下一篇精选文章',
    goTo: '跳转到精选文章',
  },
  faq: {
    kicker: '08 — 常见问题',
    title: '你可能想问的。',
    chatPrompt: '还有别的问题？',
    chatCta: '在在线聊天中提问',
    items: [
      { q: '你接哪些类型的项目？', a: '我制作交互式营销网站、产品界面、WebGL 体验和设计系统。合作方大多是希望作品既有手工质感、又保持快速与无障碍的产品团队、设计工作室和代理公司。' },
      { q: '做一个网站或 Web 应用要多少钱？', a: '聚焦型项目（例如带 WebGL 首屏的落地页）通常从 12,000 欧元起。较大的产品项目按两周一个迭代规划；在一次免费的 30 分钟沟通后，我会给出固定报价。' },
      { q: '一个项目通常需要多长时间？', a: '营销网站从启动到上线通常需要四到八周。产品与设计系统项目以迭代方式推进，第一个月内就会有可用的版本上线。' },
      { q: '你能和其他时区的团队合作吗？', a: '可以。我常驻里斯本（UTC+0），合作团队从旧金山到悉尼都有。我会与你的核心工作时间保持至少三小时重叠，并提供详尽的异步进度更新。' },
      { q: '你能让我现有的网站变快吗？', a: '当然。性能审计涵盖 Core Web Vitals、JavaScript 与图片预算以及渲染策略。你会拿到一份按优先级排序的报告，我也可以和你的团队一起落地优化。' },
      { q: '你做的网站支持无障碍吗？', a: '每个项目都以 WCAG 2.2 AA 为目标：语义化 HTML、键盘操作、可见的焦点、减少动态效果的替代方案，以及真机读屏测试。' },
    ],
  },
  contact: {
    kicker: '09 — 联系',
    title: '一起做点了不起的东西。',
    intro: '告诉我你的项目、时间线和预算。每条消息我都会在两个工作日内回复。',
    detailsTitle: '工作室',
    availability: '目前可预约 2026 年 11 月起的项目。',
    hours: '周一至周五 9:00–18:00（西欧时间）',
    form: {
      name: '你的名字',
      email: '电子邮箱',
      company: '公司（选填）',
      type: '项目类型',
      typePlaceholder: '请选择项目类型',
      types: ['营销网站', 'Web 应用 / 产品界面', 'WebGL 体验', '设计系统', '性能审计', '其他'],
      budget: '预算',
      budgets: ['< 1 万欧', '1–2.5 万欧', '2.5–5 万欧', '5 万欧以上'],
      message: '项目详情',
      messagePlaceholder: '目标、受众、时间线、参考链接……',
      files: '附件',
      dropIdle: '把需求文档或图片拖到这里，或点击选择文件',
      dropActive: '松开即可添加文件',
      dropHint: '支持 PDF、PNG、JPG、SVG、WebP · 最多 5 个文件 · 每个 10 MB 以内',
      sample: '添加示例需求文档',
      remove: '移除',
      consent: '我同意保存我的信息，以便回复我的咨询。',
      captcha: '我不是机器人',
      captchaChecking: '验证中…',
      captchaDone: '已验证',
      captchaNote: 'reCAPTCHA v2（离线演示模式）',
      submit: '发送消息',
      sending: '发送中…',
      successTitle: '消息已收到！',
      successText: '谢谢——我会在两个工作日内回复你。你的咨询副本已保存在本浏览器中。',
      another: '再发一条消息',
      charCount: '字',
      errors: {
        name: '请填写你的名字。',
        email: '请输入有效的电子邮箱。',
        type: '请选择项目类型。',
        message: '请至少写 30 个字，方便我了解你的项目。',
        consent: '请勾选同意，以便我回复你。',
        captcha: '请确认你不是机器人。',
        file: '不支持该文件类型或大小。',
        summary: '请修正标出的字段。',
      },
    },
  },
  footer: {
    cta: '有想法？聊聊吧',
    navigate: '导航',
    writing: '写作',
    connect: '社交',
    studio: '工作室',
    allPosts: '全部文章',
    tags: '按主题浏览',
    archive: '归档',
    rss: 'RSS 订阅',
    sitemap: '站点地图',
    built: '使用 Next.js、Astro 与大量咖啡构建。',
    updated: '最后更新',
    eggs: '已发现彩蛋',
    top: '回到顶部',
  },
  widgets: {
    audioTitle: '生成式 Lo-fi',
    audioSub: 'Web Audio 实时合成',
    play: '播放背景音乐',
    pause: '暂停背景音乐',
    volume: '音乐音量',
    toTop: '回到顶部',
    social: '社交主页',
    socialOpen: '展开社交链接',
    socialClose: '收起社交链接',
    chatTitle: '和 Mara 聊聊',
    chatSubtitle: '通常几分钟内回复',
    chatPlaceholder: '输入消息…',
    achievement: '成就解锁',
    achievements: {
      'night-owl': ['夜猫子', '你切换了主题。'],
      curator: ['策展人', '你打开了一个项目。'],
      dj: ['DJ', '你播放了音乐。'],
      explorer: ['探索者', '你浏览到了页面底部。'],
      'pen-pal': ['笔友', '你发送了一条消息。'],
      konami: ['复古玩家', '↑ ↑ ↓ ↓ ← → ← → B A'],
    },
  },
  chat: {
    welcome: '你好！我是 Mara 的助理 👋 可以问我档期、报价、合作流程或技术栈。',
    quick: [['档期', 'availability'], ['报价', 'pricing'], ['流程', 'process'], ['技术栈', 'stack']],
    answers: {
      availability: 'Mara 可预约 2026 年 11 月起的新项目，短期审计类工作通常可以更早开始。',
      pricing: '聚焦型项目约 1.2 万欧元起；较大的产品项目会在免费沟通后按两周迭代估算。',
      process: '初步沟通 → 方案 → 设计与原型 → 迭代开发 → 上线与交接，每周都有演示。',
      stack: '主要使用 React、Next.js、Astro、TypeScript 和 Three.js——按项目选择，而不是按习惯。',
      contact: '最快的方式是页面底部的联系表单，也可以发邮件到 hello@maraellison.dev。',
      hello: '你好！今天有什么可以帮你？',
      thanks: '不客气！还有别的问题吗？',
      fallback: '好问题！我已经转告 Mara——如果你在联系表单里留下邮箱，她会通过邮件回复。',
    },
    keywords: {
      availability: ['档期', '什么时候', '开始', '有空', '预约', 'available'],
      pricing: ['价格', '报价', '多少钱', '预算', '费用', 'price', '€'],
      process: ['流程', '怎么合作', '步骤', 'process'],
      stack: ['技术', '技术栈', 'react', 'next', 'astro', 'three', '框架'],
      contact: ['联系', '邮箱', '电话', 'email'],
      hello: ['你好', '您好', 'hi', 'hello', '嗨'],
      thanks: ['谢谢', '感谢', 'thanks'],
    },
  },
  notFound: {
    title: '页面不存在 — Mara Ellison',
    heading: '迷失在太空。',
    text: '你要找的页面飘出了轨道。我们带你回到熟悉的地方。',
    home: '返回首页',
    blog: '阅读博客',
    work: '查看精选作品',
  },
};

export default zh;
