import { CITIES, COUNTIES, STATIONS, PROVINCES } from '../data/geo-data.js';

const DICT = {
  appTitle: ['Air Quality Real-time Monitoring System', '空气质量实时监测系统'],
  appKicker: ['Air Quality', '空气质量'], appTitle2: ['Real-time Monitoring System', '实时监测系统'],
  appSub: ['National ambient air quality monitoring network', '国家环境空气质量监测网'],
  'nav.monitor': ['Real-time Monitoring', '实时监测'],
  'nav.ranking': ['Air Quality Ranking', '空气质量排名'],
  'nav.compare': ['City Comparison', '城市对比分析'],
  'nav.history': ['Historical Query', '历史数据查询'],
  dataTime: ['Data time', '数据时间'],
  nextUpdate: ['next update in', '距下次更新'],
  simNote: ['Simulated data · deterministic model of 337 cities and 1,578 stations', '模拟数据 · 337个城市、1578个国控站点确定性模型'],
  footNote: ['Demonstration data generated by a deterministic model of 337 cities, 2,895 districts/counties and 1,578 stations · AQI per HJ 633-2012 · composite index per HJ 663-2013', '演示数据由337个城市、2895个区县、1578个站点的确定性模型生成 · AQI依据HJ 633-2012 · 综合指数依据HJ 663-2013'],
  recordsN: ['{n} records', '共{n}条'],
  newHour: ['New hourly data received: {t}', '已接收最新小时数据：{t}'],

  // levels
  l0: ['Excellent', '优'], l1: ['Good', '良'], l2: ['Lightly Polluted', '轻度污染'], l3: ['Moderately Polluted', '中度污染'], l4: ['Heavily Polluted', '重度污染'], l5: ['Severely Polluted', '严重污染'],
  ls0: ['Excellent', '优'], ls1: ['Good', '良'], ls2: ['Light', '轻度'], ls3: ['Moderate', '中度'], ls4: ['Heavy', '重度'], ls5: ['Severe', '严重'],
  h0: ['Air quality is satisfactory and poses little or no risk.', '空气质量令人满意，基本无空气污染。'],
  h1: ['Acceptable; a very small number of unusually sensitive people may be affected.', '空气质量可接受，某些污染物可能对极少数异常敏感人群健康有较弱影响。'],
  h2: ['Sensitive groups may experience mild aggravation of symptoms.', '易感人群症状有轻度加剧，健康人群出现刺激症状。'],
  h3: ['Symptoms worsen for sensitive groups; heart and lungs of healthy people may be affected.', '进一步加剧易感人群症状，可能对健康人群心脏、呼吸系统有影响。'],
  h4: ['Heart and lung patients show marked symptoms; healthy people commonly affected.', '心脏病和肺病患者症状显著加剧，运动耐受力降低，健康人群普遍出现症状。'],
  h5: ['Healthy people show strong symptoms; some diseases may appear early.', '健康人群运动耐受力降低，有明显强烈症状，提前出现某些疾病。'],
  a0: ['All groups can carry on normal outdoor activities.', '各类人群可正常活动。'],
  a1: ['Unusually sensitive people should reduce outdoor activity.', '极少数异常敏感人群应减少户外活动。'],
  a2: ['Children, the elderly and heart/respiratory patients should cut long or intense outdoor exercise.', '儿童、老年人及心脏病、呼吸系统疾病患者应减少长时间、高强度的户外锻炼。'],
  a3: ['Sensitive groups avoid long or intense outdoor exercise; others reduce it.', '儿童、老年人及心脏病、呼吸系统疾病患者避免长时间、高强度的户外锻炼，一般人群适量减少户外运动。'],
  a4: ['Sensitive groups stay indoors; everyone should reduce outdoor activity.', '儿童、老年人和心脏病、肺病患者应停留在室内，停止户外运动，一般人群减少户外运动。'],
  a5: ['Sensitive groups stay indoors and avoid exertion; everyone avoids outdoor activity.', '儿童、老年人和病人应当留在室内，避免体力消耗，一般人群应避免户外活动。'],

  // generic
  city: ['City', '城市'], province: ['Province', '省份'], county: ['District / County', '区县'], station: ['Station', '站点'],
  level: ['Level', '级别'], primary: ['Primary pollutant', '首要污染物'], primaryShort: ['Primary', '首要污染物'],
  rank: ['Rank', '排名'], time: ['Time', '时间'], date: ['Date', '日期'], location: ['Location', '监测点位'],
  type: ['Type', '类型'], mean: ['Mean', '均值'], max: ['Max', '最大值'], min: ['Min', '最小值'],
  search: ['Search city…', '搜索城市…'], searchAny: ['Search city, district or station…', '搜索城市、区县或站点…'],
  none: ['—', '—'], noData: ['No data', '暂无数据'], all: ['All', '全选'], clear: ['Clear', '清空'],
  exportCsv: ['Export CSV', '导出CSV'], exportXls: ['Export Excel', '导出Excel'], exported: ['Exported {n} rows', '已导出{n}条记录'],
  hourly: ['Hourly', '小时'], daily: ['Daily', '日'], monthly: ['Monthly', '月'], annual: ['Annual', '年'],
  days: ['days', '天'], hoursUnit: ['h', '时'], loading: ['Computing…', '计算中…'],
  cumulative: ['cumulative', '累计'], today: ['Today', '今日'],
  evalSite: ['Urban', '评价点'], bgSite: ['Background', '对照点'],
  districtK: ['District', '区'], countyK: ['County', '县'], cityK: ['County-level city', '县级市'],

  // monitor
  modeHourly: ['Hourly', '小时数据'], modeDaily: ['Daily cumulative', '日累计'],
  kCities: ['Cities', '监测城市'], kStations: ['Stations', '国控站点'], kGood: ['Good or better', '优良比例'], kMean: ['Mean AQI', '平均AQI'],
  kWorst: ['Most polluted', '污染最重'], kBest: ['Cleanest', '空气最好'],
  mapTitle: ['National air quality', '全国空气质量'], mapHint: ['Click a city for details · drag the timeline or press ←/→ to replay, Space to play', '点击城市查看详情 · 拖动时间轴或按←/→回放，空格播放'],
  hourlyTrend: ['Hourly trend · last 24 h', '逐小时变化 · 近24小时'], dailyTrend: ['Daily cumulative · last 30 days', '日累计 · 近30天'],
  cumAqi: ['Daily cumulative AQI', '日累计AQI'], cumTo: ['00:00–{h}:00 cumulative', '00:00–{h}:00 累计'],
  stationsOf: ['Monitoring stations · {c}', '监测站点 · {c}'], rtRanking: ['Real-time ranking · 337 cities', '实时排名 · 337城市'],
  bgNote: ['Background sites are excluded from the city average', '对照点不参与城市均值计算'],
  backToCity: ['Back to {c}', '返回{c}'], stationView: ['Station', '站点'],
  play: ['Play', '播放'], pause: ['Pause', '暂停'], latest: ['Latest', '最新'],
  mapUnitAqi: ['AQI', 'AQI'],
  subIndex: ['IAQI', '分指数'],
  healthEffect: ['Health effects', '健康影响'], advice: ['Advice', '建议措施'],

  // ranking
  g74: ['74 Cities', '74城市'], g168: ['168 Cities', '168城市'], g337: ['337 Cities', '337城市'],
  gFw: ['Fenwei Plain · Cities', '汾渭平原城市'], gFwc: ['Fenwei Plain · Districts & Counties', '汾渭平原区县'],
  gFwShort: ['Fenwei cities', '汾渭城市'], gFwcShort: ['Fenwei counties', '汾渭区县'],
  pDaily: ['Daily', '日排名'], pMonthly: ['Monthly cumulative', '月累计'], pAnnual: ['Annual cumulative', '年累计'],
  rankBy: ['Rank by', '排名依据'], byAqi: ['AQI', 'AQI'], byCi: ['Composite index', '综合指数'], byPm25: ['PM2.5', 'PM2.5'], byGood: ['Good-day rate', '优良天数比例'],
  orderBest: ['Best first', '由好到差'], orderWorst: ['Worst first', '由差到好'],
  ci: ['Composite index', '综合指数'], ciShort: ['CI', '综合指数'], yoy: ['YoY', '同比'], goodRate: ['Good-day rate', '优良天数比例'], goodDays: ['Good days', '优良天数'],
  periodInfo: ['{from} – {to} · {n} days', '{from} 至 {to} · 共{n}天'], periodToday: ['{d} · cumulative to {h}:00', '{d} · 累计至{h}:00'],
  focus: ['Focus', '关注'], focusRank: ['ranks <b>{r}</b> of {n}', '排名第<b>{r}</b>位 / {n}'],
  groupMean: ['Group mean', '组平均'], groupGood: ['Good-day rate', '优良天数比例'],
  best10: ['Best 10', '前10名'], worst10: ['Worst 10', '后10名'], rankMap: ['Spatial distribution', '空间分布'],
  critNote: ['Daily ranking uses the daily AQI; cumulative rankings use the composite index (HJ 663-2013).', '日排名依据日AQI；累计排名依据环境空气质量综合指数（HJ 663-2013）。'],
  year: ['Year', '年份'], month: ['Month', '月份'],
  o3per90: ['O₃-8h 90th pct', 'O₃-8h第90百分位'], coper95: ['CO 95th pct', 'CO第95百分位'],

  // compare
  region: ['Region', '区域'], customSel: ['Custom', '自定义'], addCity: ['Add any city…', '添加任意城市…'],
  selected: ['{n} selected', '已选{n}个'], regionCities: ['Cities in region', '区域城市'], provinceList: ['Provinces', '按省份'],
  gran: ['Granularity', '时间粒度'], range: ['Range', '时间范围'], indicator: ['Indicator', '指标'],
  trend: ['Trend comparison', '趋势对比'], heat: ['Region summary', '区域汇总'], profile: ['Pollutant profile', '污染物构成'],
  profileNote: ['Ci / Si vs. annual standard', '单项指数 Ci/Si（年均二级标准）'],
  stats: ['Statistical analysis', '统计分析'], exceed: ['Over standard', '超标次数'], rankSel: ['Rank', '排名'],
  lastH: ['{n} h', '近{n}小时'], lastD: ['{n} days', '近{n}天'], lastM: ['{n} months', '近{n}个月'], allYears: ['{a}–{b}', '{a}–{b}年'],
  pickHint: ['Select cities on the left to compare', '请在左侧选择要对比的城市'], maxHint: ['Showing the first {n} series', '仅显示前{n}条曲线'],
  avgComp: ['Mean', '均值'],

  // history
  qLevel: ['Query level', '查询层级'], qCity: ['City', '城市'], qCounty: ['District / County', '区县'], qStation: ['Station', '站点'],
  qProvince: ['Province', '省份'], qCities: ['Cities', '城市'], qCounties: ['Districts / counties', '区县'], qStations: ['Stations', '站点'],
  from: ['From', '开始日期'], to: ['To', '结束日期'], quick: ['Quick range', '快捷时段'],
  q7: ['7 days', '近7天'], q30: ['30 days', '近30天'], qMonth: ['This month', '本月'], qYear: ['This year', '本年'], qPrevYear: ['Last year', '去年'],
  fields: ['Fields', '查询项目'], doQuery: ['Query', '查询'], reset: ['Reset', '重置'],
  results: ['Query results', '查询结果'], records: ['Records', '记录数'], meanAqi: ['Mean AQI', '平均AQI'], maxAqi: ['Max AQI', '最大AQI'],
  overDays: ['Over standard', '超标'], topPrimary: ['Most frequent primary', '主要首要污染物'],
  pageInfo: ['{a}–{b} of {n}', '第{a}-{b}条 / 共{n}条'], perPage: ['per page', '条/页'],
  hourLimit: ['Hourly queries are limited to 31 days — range trimmed.', '小时数据查询范围不超过31天，已自动截取。'],
  selCount: ['{n} of {m}', '{n}/{m}'], pickSome: ['Select at least one location', '请至少选择一个点位'],
  levelDist: ['Level distribution', '级别分布'], queryTrend: ['AQI trend', 'AQI变化趋势'],
  qEmpty: ['Set conditions and press Query', '设置查询条件后点击查询'],
  monthAvg: ['monthly mean', '月均值'],
};

let lang = 'en';
try {
  const q = new URLSearchParams(location.search).get('lang');
  lang = q === 'zh' || q === 'en' ? q : localStorage.getItem('aq-lang') || 'en';
} catch (e) { /* storage unavailable */ }

export const getLang = () => lang;
export function setLang(l) {
  lang = l;
  try { localStorage.setItem('aq-lang', l); } catch (e) { /* ignore */ }
  document.documentElement.lang = l === 'zh' ? 'zh-CN' : 'en';
}

export function t(key, vars) {
  const e = DICT[key];
  let s = e ? e[lang === 'zh' ? 1 : 0] : key;
  if (vars) for (const k in vars) s = s.split('{' + k + '}').join(vars[k]);
  return s;
}

export const levelName = (i, short = false) => (i < 0 ? t('none') : t((short ? 'ls' : 'l') + i));
export const cityName = (i) => CITIES[i][lang === 'zh' ? 0 : 1];
export const provName = (i) => PROVINCES[i][lang === 'zh' ? 0 : 1];
export const countyName = (i) => COUNTIES[i][lang === 'zh' ? 0 : 1];
export const stationName = (i) => STATIONS[i][lang === 'zh' ? 0 : 1];
export function entityName(e, withCity = false) {
  if (e.t === 'city') return cityName(e.i);
  const own = e.t === 'county' ? countyName(e.i) : stationName(e.i);
  if (!withCity) return own;
  const ci = e.t === 'county' ? COUNTIES[e.i][2] : STATIONS[e.i][2];
  return cityName(ci) + (lang === 'zh' ? '·' : ' · ') + own;
}

export const POL_LABEL = ['PM2.5', 'PM10', 'O₃', 'NO₂', 'SO₂', 'CO'];
export const POL_PLAIN = ['PM2.5', 'PM10', 'O3', 'NO2', 'SO2', 'CO'];
export const unitOf = (p) => (p === 5 ? 'mg/m³' : 'μg/m³');
export const fmtNum = (v, digits = 0) => (v == null || Number.isNaN(v) ? '—' : Number(v).toLocaleString(lang === 'zh' ? 'zh-CN' : 'en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits }));
export const fmtVal = (p, v) => (v == null || Number.isNaN(v) ? '—' : p === 5 ? v.toFixed(1) : String(Math.round(v)));
export const primaryLabel = (list) => (list && list.length ? list.map((p) => POL_LABEL[p]).join(', ') : t('none'));
