// The eight invented worlds of the Vesper system, plus the reference Earth used on the size chart.
// Colours are sRGB hex; `visual` is the radius used in the system view, `radius` the "true" size in Earth radii.

export const STAR = {
  name: 'Vesper',
  cls: 'G-type dwarf · 0.94 solar masses',
};

export const PLANETS = [
  {
    id: 'vitrea', name: 'Vitrea', epithet: 'The Glass World', cls: 'Crystalline silicate world',
    accent: '#8fe3ff', type: 'crystal', shape: 'sphere',
    orbit: { r: 13, phase: 0.8, incl: 0.03 }, visual: 1.25, tilt: 0.21, spin: 0.07, sunIntensity: 2.1,
    view: { dist: 4.1, az: 38, el: 12 },
    params: {
      seed: [3.1, 7.7, 1.3], scale: 2.0, sea: 0, temp: 0.95, bump: 0.35, glow: 1.0,
      colA: '#5fd0ff', colB: '#b69cff', colC: '#fff2d2', colD: '#1b2a4a', colE: '#ffffff', glowCol: '#ff8a3d',
      atmoCol: '#bfe7ff', atmoStr: 0.35,
    },
    atmosphere: { color: '#a9dcff', sunset: '#ffb38a', thickness: 0.06, strength: 0.75 },
    stats: { radius: 0.71, gravity: 0.64, day: '31 h 12 m', dayHours: 31.2, year: '41 days', yearDays: 41, temp: '+612 °C', tempC: 612, pressure: '0.3 bar', moons: 0, distance: '0.21 AU', distanceAU: 0.21 },
    atmoComp: [['Silicate vapour', 58], ['Carbon monoxide', 23], ['Sodium', 11], ['Other', 8]],
    tagline: 'Where it rains glass — sideways.',
    lore: 'Vitrea’s crust is one continuous crystal lattice, fractured into facets the size of countries. Silicate winds boil off the dayside, cool as they cross into night, and fall as a fine, singing rain of glass. From orbit the planet flashes like a slow mirror-ball each time a new facet turns toward Vesper.',
    pois: [
      { name: 'The Prism Steppes', lat: 18, lon: -30, text: 'Facets aligned so precisely that sunlight splits into standing rainbows several kilometres tall.' },
      { name: 'Chime Fields', lat: -34, lon: 70, text: 'Hollow crystal spires ring under the glass rain, producing a constant, choir-like drone.' },
      { name: 'The Clear Deep', lat: 52, lon: 150, text: 'A window of flawless crystal through which you can watch the molten mantle glowing 40 km below.' },
    ],
    note: { text: 'We landed at dawn and the whole horizon rang like a struck wineglass.', by: 'Pilot Noor Hadley, survey vessel Kestrel' },
    ratings: { wonder: 5, comfort: 1, danger: 4 },
    sound: 'glass',
  },
  {
    id: 'kintsugi', name: 'Kintsugi', epithet: 'The Mended World', cls: 'Fractured volcanic world',
    accent: '#f4b94a', type: 'lava', shape: 'sphere',
    orbit: { r: 18.5, phase: 2.6, incl: -0.02 }, visual: 1.5, tilt: 0.12, spin: 0.05, sunIntensity: 1.9,
    view: { dist: 4.0, az: 98, el: 16 },
    params: {
      seed: [11.2, 4.4, 8.9], scale: 1.6, sea: 0, temp: 0.8, bump: 0.25, glow: 1.0,
      colA: '#141218', colB: '#3b3431', colC: '#e5ad4b', colD: '#000000', colE: '#000000', glowCol: '#ffae3a',
      atmoCol: '#ff9d5c', atmoStr: 0.25,
    },
    atmosphere: { color: '#ffae70', sunset: '#ff6a3a', thickness: 0.05, strength: 0.55 },
    moons: [{ name: 'Shard', size: 0.2, dist: 2.6, speed: 0.22, incl: 0.2, phase: 1.0, colA: '#2a2622', colB: '#6b5f55', seed: 3 }],
    stats: { radius: 1.08, gravity: 1.12, day: '19 h 40 m', dayHours: 19.7, year: '88 days', yearDays: 88, temp: '+188 °C', tempC: 188, pressure: '4.1 bar', moons: 1, distance: '0.38 AU', distanceAU: 0.38 },
    atmoComp: [['Carbon dioxide', 71], ['Sulfur dioxide', 17], ['Nitrogen', 9], ['Other', 3]],
    tagline: 'Broken once. Healed in gold.',
    lore: 'Four hundred million years ago a collision cracked Kintsugi into a thousand drifting plates — and it never quite finished breaking. Molten ore rich in gold and copper welled up through every seam and cooled into luminous veins, so the whole planet looks like porcelain repaired by a patient god. The seams still glow. The planet is still healing.',
    pois: [
      { name: 'The Great Seam', lat: 8, lon: 20, text: 'A 9,000 km fissure of liquid metal, bright enough to read by from the moon Shard.' },
      { name: 'Obsidian Mirror', lat: -40, lon: 115, text: 'A continental plate polished glass-smooth by millennia of ash storms. It reflects the stars.' },
      { name: 'The Mender’s Vent', lat: 47, lon: -80, text: 'Where new gold rises fastest, pulsing like a heartbeat every 71 minutes.' },
    ],
    note: { text: 'It is the only world I have seen that looks proud of its scars.', by: 'Geologist Ama Okafor' },
    ratings: { wonder: 5, comfort: 1, danger: 5 },
    sound: 'forge',
  },
  {
    id: 'hespera', name: 'Hespera', epithet: 'The Twilight Ring', cls: 'Tidally locked terrestrial',
    accent: '#ffa565', type: 'eyeball', shape: 'sphere', locked: true,
    orbit: { r: 24, phase: 4.4, incl: 0.02 }, visual: 1.4, tilt: 0, spin: 0, sunIntensity: 1.9,
    view: { dist: 4.0, az: 58, el: 16 },
    params: {
      seed: [5.5, 2.2, 9.1], scale: 1.9, sea: 0, temp: 0.6, bump: 0.22, glow: 1.0,
      colA: '#fff0d6', colB: '#d56f39', colC: '#5c8f37', colD: '#e3edf7', colE: '#7fa6c9', glowCol: '#ff5a1f',
      atmoCol: '#9cc9ff', atmoStr: 0.4,
    },
    ambient: [0.03, 0.036, 0.052],
    clouds: { style: 'eye', cover: 0.6, scale: 2.2, seed: [1.3, 8.2, 4.4], opacity: 0.92, tint: '#ffffff', speed: 0 },
    atmosphere: { color: '#8fc1ff', sunset: '#ff9c66', thickness: 0.065, strength: 1.0 },
    stats: { radius: 0.93, gravity: 0.89, day: '23 days (locked)', dayHours: 552, year: '23 days', yearDays: 23, temp: '+96 / −140 °C', tempC: 14, pressure: '0.9 bar', moons: 0, distance: '0.52 AU', distanceAU: 0.52 },
    atmoComp: [['Nitrogen', 78], ['Carbon dioxide', 14], ['Argon', 5], ['Oxygen', 3]],
    tagline: 'Eternal noon on one side, endless night on the other — and a ring of dusk between.',
    lore: 'Hespera keeps one face forever turned toward Vesper. Its dayside is a blinding salt desert crowned by a permanent storm; its nightside is a glacier the size of a continent that has never seen the sun. Life clings to the ring of permanent dusk in between: a band of forest a few hundred kilometres wide that wraps the entire planet, where the sun sits on the horizon forever and every hour is golden hour.',
    pois: [
      { name: 'The Eye', lat: 0, lon: 0, text: 'A hurricane pinned above the substellar point for two billion years. Its calm centre is a salt pan hotter than an oven.' },
      { name: 'The Dusk Belt', lat: 12, lon: 88, text: 'Forests 40,000 km long and never more than 600 km wide, their leaves all turned toward the same unmoving sunset.' },
      { name: 'Longnight Glacier', lat: -10, lon: 180, text: 'Ice three kilometres thick, fed by snow carried over from the dayside on endless winds.' },
    ],
    note: { text: 'Nobody on Hespera says good morning. They ask which way you are walking.', by: 'Travel writer Iris Calder' },
    ratings: { wonder: 4, comfort: 3, danger: 2 },
    sound: 'dusk',
  },
  {
    id: 'halcyon', name: 'Halcyon', epithet: 'The Archipelago World', cls: 'Temperate ocean world',
    accent: '#4fd6c8', type: 'terran', shape: 'sphere',
    orbit: { r: 30.5, phase: 0.3, incl: -0.01 }, visual: 1.63, tilt: 0.36, spin: 0.06, sunIntensity: 1.85,
    view: { dist: 4.0, az: 42, el: 12 },
    params: {
      seed: [2.7, 9.4, 6.1], scale: 1.75, sea: 0.13, temp: 0.62, bump: 0.18, glow: 1.0, reef: 1.3, lights: 0,
      colA: '#062449', colB: '#15a1b5', colC: '#3e8a3b', colD: '#8b7a56', colE: '#e8d9a8', glowCol: '#39fff0',
      atmoCol: '#79b8ff', atmoStr: 0.55,
    },
    clouds: { style: 'swirl', cover: 0.48, scale: 1.6, seed: [4.2, 1.9, 7.3], opacity: 0.95, tint: '#ffffff', speed: 0.012, shadow: 0.45 },
    atmosphere: { color: '#6fb2ff', sunset: '#ff9466', thickness: 0.07, strength: 1.15 },
    moons: [
      { name: 'Ebb', size: 0.24, dist: 2.9, speed: 0.16, incl: 0.12, phase: 0.4, colA: '#6e6a66', colB: '#bdb6ad', seed: 7 },
      { name: 'Flow', size: 0.15, dist: 3.8, speed: 0.11, incl: -0.2, phase: 3.1, colA: '#7a6a5c', colB: '#d2c2ae', seed: 13 },
    ],
    stats: { radius: 1.27, gravity: 1.06, day: '26 h 05 m', dayHours: 26.1, year: '1.4 years', yearDays: 511, temp: '+21 °C', tempC: 21, pressure: '1.2 bar', moons: 2, distance: '1.05 AU', distanceAU: 1.05 },
    atmoComp: [['Nitrogen', 72], ['Oxygen', 24], ['Argon', 3], ['Water vapour', 1]],
    tagline: 'Ten thousand islands, one endless sea.',
    lore: 'Halcyon is ninety-four percent ocean: a warm, shallow sea scattered with more than ten thousand volcanic islands. Its two moons, Ebb and Flow, raise tides of forty metres, so the coastlines breathe twice a day. At night the reefs glow soft cyan as trillions of luminous polyps wake to feed, tracing every island in light.',
    pois: [
      { name: 'The Thousand Stairs', lat: 14, lon: -20, text: 'A chain of terraced atolls that flood and drain with every tide, like a staircase climbing out of the sea.' },
      { name: 'Lantern Reef', lat: -22, lon: 60, text: 'The brightest reef system on the planet — visible from orbit on moonless nights.' },
      { name: 'The Drowned Crown', lat: 38, lon: 140, text: 'Twelve islands on the rim of a sunken caldera, arranged in an almost perfect circle.' },
    ],
    note: { text: 'We stayed three weeks and I still couldn’t tell you where one island ends and the sea begins.', by: 'Marine biologist Tomas Reyes' },
    ratings: { wonder: 4, comfort: 5, danger: 1 },
    sound: 'ocean',
  },
  {
    id: 'ouroboros', name: 'Ouroboros', epithet: 'The Ring World', cls: 'Toroidal planet',
    accent: '#a6d86b', type: 'terran', shape: 'torus',
    orbit: { r: 38, phase: 3.3, incl: 0.03 }, visual: 2.0, tilt: 0.3, spin: 0.16, sunIntensity: 1.85,
    view: { dist: 4.7, az: 34, el: 38 },
    params: {
      seed: [8.8, 3.6, 2.2], scale: 2.1, sea: 0.02, temp: 0.55, bump: 0.2, glow: 1.0, reef: 0, lights: 1.2,
      colA: '#0b3050', colB: '#2a8fa6', colC: '#6b8f3c', colD: '#9a7b52', colE: '#d8c290', glowCol: '#ffc36b',
      atmoCol: '#8fc4ff', atmoStr: 0.5,
    },
    clouds: { style: 'swirl', cover: 0.4, scale: 2.2, seed: [9.1, 2.3, 5.5], opacity: 0.9, tint: '#ffffff', speed: 0.02, shadow: 0.35 },
    atmosphere: { color: '#86bdff', sunset: '#ff9466', thickness: 0.12, strength: 1.0 },
    moons: [{ name: 'Needle', size: 0.1, dist: 0.38, speed: 0.5, incl: 0, phase: 0, colA: '#8a8078', colB: '#d6cbbd', seed: 21, through: true }],
    stats: { radius: 3.55, gravity: 0.8, gravityText: '0.4 – 1.2 g', gravityRange: [0.4, 1.2], day: '3 h 30 m', dayHours: 3.5, year: '1.9 years', yearDays: 694, temp: '+12 °C', tempC: 12, pressure: '1.0 bar', moons: 3, distance: '1.6 AU', distanceAU: 1.6 },
    atmoComp: [['Nitrogen', 70], ['Oxygen', 26], ['Argon', 3], ['Other', 1]],
    tagline: 'A world with a hole in the middle.',
    lore: 'Ouroboros is what happens when a planet spins too fast to stay round. Flattened by a three-hour day into a ring 45,000 km across, it has no poles, a sky split by its own far side, and an inner coast — the Hollow Shore — where the horizon curves up instead of down. From there, the rest of the world hangs overhead like a bridge of oceans and cities.',
    pois: [
      { name: 'The Hollow Shore', u: 30, v: 180, text: 'The inner equator. Look up and the far side of the planet arches across the sky; at night its cities form a second Milky Way.' },
      { name: 'The Outer Rim', u: 200, v: 0, text: 'The fastest-moving ground on the planet: winds never drop below 150 km/h and gravity peaks at 1.2 g.' },
      { name: 'Needle’s Pass', center: true, text: 'The little moon Needle threads the hole twice a day, eclipsing the Hollow Shore for eleven minutes at a time.' },
    ],
    note: { text: 'At dusk the other half of the world lights up above your head, one city at a time.', by: 'Cartographer Lena Voss' },
    ratings: { wonder: 5, comfort: 3, danger: 2 },
    sound: 'loop',
  },
  {
    id: 'aurelia', name: 'Aurelia', epithet: 'The Gilded Giant', cls: 'Ringed gas giant',
    accent: '#e9c47e', type: 'gas', shape: 'sphere',
    orbit: { r: 51, phase: 5.4, incl: -0.02 }, visual: 4.25, tilt: 0.42, spin: 0.09, sunIntensity: 1.9,
    view: { dist: 7.6, az: 28, el: 20 },
    params: {
      seed: [1.1, 6.6, 3.3], scale: 1.4, sea: 0, temp: 0.5, bump: 0, glow: 0,
      colA: '#f4e4c0', colB: '#d9a35f', colC: '#a5553a', colD: '#6b4a3a', colE: '#e2703b', glowCol: '#000000',
      atmoCol: '#ffe0b0', atmoStr: 0.35,
      storm: { lat: -22, lon: 40, strength: 1.0, size: 0.22 }, bands: 11, turbulence: 0.9,
    },
    atmosphere: { color: '#ffd9a0', sunset: '#ff9a5a', thickness: 0.035, strength: 0.6 },
    rings: { inner: 1.35, outer: 2.35, colA: '#f6e2b6', colB: '#b89262' },
    moons: [
      { name: 'Lyre', size: 0.07, dist: 2.7, speed: 0.12, incl: 0.02, phase: 0.8, colA: '#8e8a86', colB: '#e0dad0', seed: 31 },
      { name: 'Ossa', size: 0.1, dist: 3.3, speed: 0.08, incl: 0.1, phase: 2.9, colA: '#7a5e48', colB: '#c9a27c', seed: 37 },
      { name: 'Pell', size: 0.06, dist: 4.0, speed: 0.06, incl: -0.08, phase: 4.6, colA: '#6d6d74', colB: '#c5c6cf', seed: 41 },
    ],
    stats: { radius: 8.6, gravity: 2.31, day: '9 h 51 m', dayHours: 9.85, year: '11.8 years', yearDays: 4310, temp: '−128 °C', tempC: -128, pressure: '—', moons: 47, distance: '4.2 AU', distanceAU: 4.2 },
    atmoComp: [['Hydrogen', 86], ['Helium', 13], ['Methane', 0.6], ['Ammonia', 0.4]],
    tagline: 'A storm the size of four Earths, wearing a crown of ice.',
    lore: 'Aurelia’s bands of cream, amber and rust are cloud decks of ammonia and sulfur racing in opposite directions at 500 km/h. Its Great Amber Storm has raged for at least three thousand years. The rings — water ice dusted with gold-tinted silicates — are 280,000 km wide and in places only thirty metres thick.',
    pois: [
      { name: 'The Great Amber Storm', lat: -22, lon: 40, text: 'An anticyclone four times wider than Earth, turning once every six days.' },
      { name: 'The Weave', lat: 30, lon: -60, text: 'A latitude where two opposing jet streams braid into lace-like chains of vortices.' },
      { name: 'Pearl Belt', lat: 3, lon: 160, text: 'The bright equatorial zone, where fresh ammonia ice clouds catch the light like pearl.' },
    ],
    note: { text: 'From the ring plane, the storm looks back at you. You get used to it. Mostly.', by: 'Ring miner Dex Aurand' },
    ratings: { wonder: 5, comfort: 1, danger: 4 },
    sound: 'gas',
  },
  {
    id: 'noctiluca', name: 'Noctiluca', epithet: 'The Glowing World', cls: 'Bioluminescent jungle world',
    accent: '#b58cff', type: 'glow', shape: 'sphere',
    orbit: { r: 64, phase: 1.7, incl: 0.02 }, visual: 1.85, tilt: 0.25, spin: 0.045, sunIntensity: 0.85,
    view: { dist: 4.0, az: 118, el: 10 },
    params: {
      seed: [7.3, 1.4, 5.8], scale: 1.8, sea: -0.05, temp: 0.4, bump: 0.25, glow: 1.1,
      colA: '#24174a', colB: '#3a2266', colC: '#04121b', colD: '#ff4fd8', colE: '#1de9d0', glowCol: '#4fc3ff',
      atmoCol: '#8a6cff', atmoStr: 0.5,
    },
    ambient: [0.03, 0.02, 0.05],
    clouds: { style: 'swirl', cover: 0.25, scale: 1.4, seed: [2.2, 6.1, 3.9], opacity: 0.6, tint: '#d8c8ff', speed: 0.01, shadow: 0.3 },
    atmosphere: { color: '#8f6bff', sunset: '#ff5fb0', thickness: 0.07, strength: 1.1 },
    moons: [
      { name: 'Wisp', size: 0.12, dist: 2.8, speed: 0.14, incl: 0.3, phase: 0.2, colA: '#4b4460', colB: '#9a90b8', seed: 51 },
      { name: 'Ember', size: 0.08, dist: 3.6, speed: 0.1, incl: -0.1, phase: 3.7, colA: '#5a4a52', colB: '#b09aa6', seed: 57 },
    ],
    stats: { radius: 1.62, gravity: 1.31, day: '41 h', dayHours: 41, year: '23 years', yearDays: 8400, temp: '−4 °C', tempC: -4, pressure: '2.6 bar', moons: 4, distance: '7.9 AU', distanceAU: 7.9 },
    atmoComp: [['Nitrogen', 61], ['Hydrogen', 21], ['Methane', 12], ['Argon', 6]],
    tagline: 'Too far from its star for daylight — so life makes its own.',
    lore: 'Noctiluca receives less than two percent of the light that Earth does. Its forests grow on geothermal heat instead, and nearly everything alive gives off light: rivers of luminous plankton, root networks that pulse in slow waves of blue and violet, fungal mats that flicker in patterns biologists have started, nervously, to call conversations.',
    pois: [
      { name: 'The Pulse Forest', lat: 20, lon: 30, text: 'A single organism spanning a continent. Its glow ripples from coast to coast in eleven-minute waves.' },
      { name: 'Cerulean Delta', lat: -18, lon: 120, text: 'Where glowing rivers meet the black sea and the plankton bloom spreads for a thousand kilometres.' },
      { name: 'The Listening Grove', lat: 44, lon: -110, text: 'Fungal towers that answer a flashlight blinking in sequence — usually with the same sequence, one step longer.' },
    ],
    note: { text: 'We switched off our lamps on the first night and never switched them on again.', by: 'Botanist Sefa Lindqvist' },
    ratings: { wonder: 5, comfort: 2, danger: 3 },
    sound: 'bio',
  },
  {
    id: 'borealis', name: 'Borealis', epithet: 'The Singing Ice', cls: 'Frozen super-Earth',
    accent: '#7ff0c8', type: 'ice', shape: 'sphere',
    orbit: { r: 74, phase: 3.9, incl: -0.03 }, visual: 2.12, tilt: 0.3, spin: 0.05, sunIntensity: 1.5,
    view: { dist: 4.0, az: 80, el: 24 },
    params: {
      seed: [4.9, 8.1, 2.6], scale: 1.7, sea: -0.12, temp: 0.1, bump: 0.2, glow: 0.8,
      colA: '#f4f8ff', colB: '#cfe2f4', colC: '#8db3d8', colD: '#1f5c9c', colE: '#ffffff', glowCol: '#58f0ff',
      atmoCol: '#a8d8ff', atmoStr: 0.45,
    },
    clouds: { style: 'swirl', cover: 0.18, scale: 1.3, seed: [6.6, 3.1, 8.8], opacity: 0.55, tint: '#eaf4ff', speed: 0.008, shadow: 0.2 },
    atmosphere: { color: '#a0d4ff', sunset: '#c9a0ff', thickness: 0.06, strength: 0.8 },
    aurora: { a: '#3dff95', b: '#ff5fb8', strength: 1.4 },
    moons: [
      { name: 'Rime', size: 0.14, dist: 2.7, speed: 0.13, incl: 0.25, phase: 1.3, colA: '#9fb0c0', colB: '#eef4fa', seed: 61 },
      { name: 'Hoar', size: 0.09, dist: 3.5, speed: 0.09, incl: -0.15, phase: 4.2, colA: '#8a96a3', colB: '#dfe7ef', seed: 67 },
    ],
    stats: { radius: 2.14, gravity: 1.58, day: '17 h 20 m', dayHours: 17.3, year: '38 years', yearDays: 13900, temp: '−182 °C', tempC: -182, pressure: '0.6 bar', moons: 2, distance: '12.4 AU', distanceAU: 12.4 },
    atmoComp: [['Nitrogen', 90], ['Methane', 7], ['Carbon monoxide', 2], ['Neon', 1]],
    tagline: 'A frozen world under a sky on fire.',
    lore: 'Borealis is sheathed in nitrogen ice kilometres thick, split by blue canyons that ring and groan as the ice shifts. A magnetic field far stronger than Earth’s funnels Vesper’s solar wind into auroras so intense they are visible even from the dayside, shimmering green and rose across a third of the sky.',
    pois: [
      { name: 'The Choir Canyons', lat: -12, lon: 30, text: 'Crevasses hundreds of kilometres long where shifting ice sings in slow harmonic tones.' },
      { name: 'Geyser Row', lat: 24, lon: 120, text: 'A line of cryovolcanoes jetting nitrogen plumes eight kilometres into the sky.' },
      { name: 'The Crown', lat: 70, lon: -40, text: 'The northern auroral oval, 4,000 km across and never, ever dark.' },
    ],
    note: { text: 'The ice hums at forty-three hertz. After a week, you start humming with it.', by: 'Acoustician Mirela Stoica' },
    ratings: { wonder: 4, comfort: 1, danger: 3 },
    sound: 'ice',
  },
];

export const EARTH_REF = {
  id: 'earth', name: 'Earth', epithet: 'For scale', cls: 'Reference', reference: true,
  accent: '#7fb6ff', type: 'terran', shape: 'sphere',
  orbit: { r: 0, phase: 0, incl: 0 }, visual: 1.0, tilt: 0.41, spin: 0.05, sunIntensity: 1.85,
  view: { dist: 4.0, az: 40, el: 10 },
  params: {
    seed: [13.3, 2.1, 7.7], scale: 1.3, sea: 0.02, temp: 0.5, bump: 0.15, glow: 0, reef: 0, lights: 0,
    colA: '#0a2a55', colB: '#1f6f9a', colC: '#3f7a35', colD: '#8a7650', colE: '#d9c79a', glowCol: '#ffcf80',
    atmoCol: '#79b8ff', atmoStr: 0.55,
  },
  clouds: { style: 'swirl', cover: 0.45, scale: 1.5, seed: [1.1, 2.2, 3.3], opacity: 0.9, tint: '#ffffff', speed: 0.01, shadow: 0.35 },
  atmosphere: { color: '#6fb2ff', sunset: '#ff9466', thickness: 0.07, strength: 1.0 },
  stats: { radius: 1, gravity: 1, day: '24 h', dayHours: 24, year: '1 year', yearDays: 365.25, temp: '+15 °C', tempC: 15, distance: '1 AU', distanceAU: 1 },
};

export const METRICS = [
  { id: 'radius', label: 'Size', fmt: (s) => `${s.radius.toFixed(2)} × Earth` },
  { id: 'gravity', label: 'Gravity', fmt: (s) => s.gravityText || `${s.gravity.toFixed(2)} g` },
  { id: 'tempC', label: 'Temperature', fmt: (s) => `${s.tempC > 0 ? '+' : s.tempC < 0 ? '−' : ''}${Math.abs(Math.round(s.tempC))} °C` },
  { id: 'dayHours', label: 'Day length', fmt: (s) => (s.dayHours >= 100 ? `${Math.round(s.dayHours / 24)} days` : `${s.dayHours.toFixed(1)} h`) },
  { id: 'distanceAU', label: 'Distance', fmt: (s) => `${s.distanceAU} AU` },
];
